### ISSUE TITLE
Swagger plugin fails if rpc input/output do not rely on "uses" statement

### ISSUE THREAD

**Issue by GermanoSMO** [ict-strauss/COP#3]
This issue is apparently similar to the issue #2, the difference being that here the context is the yang "rpc" statement.

The sample codes are the following:

``` yang
        // SAMPLE SNIPPET #1
    grouping dummy {
       leaf alpha {
           type string; }
       leaf beta {
           type string; }
        }

    grouping dummy2 {
       leaf delta {
           type string; }
       leaf epsilon {
           type string; }
        }

    rpc dummyCall {
        description "test";
        input {
            leaf gamma {
                type int8;
                }
            }
        output {
            uses dummy2;
            }   
        }
```

``` yang
        // SAMPLE SNIPPET #2
    grouping dummy {
       leaf alpha {
           type string; }
       leaf beta {
           type string; }
        }

    grouping dummy2 {
       leaf delta {
           type string; }
       leaf epsilon {
           type string; }
        }

    rpc dummyCall {
        description "test";
        input {
            uses dummy;
            }
        output {
            leaf gamma {
                type int8;
                }
            }   
        }
```

In both cases, the pyang -f swagger command fails with this error message (seems the same as for issue #2):

> Traceback (most recent call last):
> File "c:/Python34/Scripts/pyang", line 403, in &lt;module&gt; run()
> File "c:/Python34/Scripts/pyang", line 377, in run emit_obj.emit(ctx, modules, fd)
> File "c:\Python34\lib\site-packages\pyang/plugins\swagger.py", line 78, in emit
>        emit_swagger_spec(ctx, modules, fd, ctx.opts.path)
> File "c:\Python34\lib\site-packages\pyang/plugins\swagger.py", line 148, in emit_swagger_spec
>        gen_apis(chs, path, model['paths'], definitions)
> File "c:\Python34\lib\site-packages\pyang/plugins\swagger.py", line 318, in gen_apis
>        gen_api_node(child, path, apis, definitions)
> File "c:\Python34\lib\site-packages\pyang/plugins\swagger.py", line 363, in gen_api_node
>        ref_model[0].arg)}
> IndexError: list index out of range

Python 3.4.3
pyang 1.5
swapper.py as of Nov. 5, 2015 (latest release with #1 fixes)

**Comment by GermanoSMO** [comment]
Specific issue successfuly addressed (so it can be closed). 
However the fix introduced regressions to be investigated.
